### ISSUE TITLE
休憩申込画面

### ISSUE THREAD

**Issue by kikutou** [kikutou/laravel_attendance_system#4]
- https://jqueryui.com/datepicker/このページを参照して、データピッカーの機能をjqueryで実現する  
- 時間と分数をセレクターに変更する。時間は1時間ごとに0時から24時まで選択できる。分数は0-45、15分間隔で選択できる。

**Comment by kikutou** [comment]
記録成功の場合、メッセージを連れて、ホームページにリダイレクトさせる。

**Comment by attilaCadabra** [comment]
push済み。確認お願いします。

**Comment by attilaCadabra** [comment]
2019年2月4日(月) 11:07 kiku <notifications@github.com>:
